CHANGE_ROUND_DECIMALS = 2
FEE_ROUND_DECIMALS = 2
USD_LIQUIDITY_ROUND_DECIMALS = 0
USD_VOLUME_ROUND_DECIMALS = 0
APR_ROUND_DECIMALS = 2

LIQUIDITY_ROUND_SIGNIFICANT = 8
PRICE_ROUND_SIGNIFICANT = 4
AMOUNT_ROUND_SIGNIFICANT = 4
